/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegio.josefelixrestrepo.acw.interfaz;

import colegio.josefelixrestrepo.acw.basededatos.Administrador;
import colegio.josefelixrestrepo.acw.basededatos.Animal;
import colegio.josefelixrestrepo.acw.logica.AnimalLogica;

import javax.swing.*;
import java.util.List;

/**
 *
 * @author nancho313
 */
public class AnimalAdministradorPanel extends javax.swing.JPanel {

    private Administrador administrador;
    private AnimalLogica animalLogica;

    /**
     * Creates new form AnimalAdministradorPanel
     */
    public AnimalAdministradorPanel() {
        initComponents();
        setSize(534,487);
    }

    public AnimalAdministradorPanel(Administrador administrador){

        this.administrador = administrador;
        this.animalLogica = new AnimalLogica();
        initComponents();
        setSize(534,487);
        this.listaAnimales.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        actualizarListadoAnimales();
    }

    public void actualizarListadoAnimales(){

        List<Animal> animales = animalLogica.obtenerTodosLosAnimales();
        Animal[] animalData = null;
        if(animales != null){

            animalData = new Animal[animales.size()];
            this.listaAnimales.setListData(animales.toArray(animalData));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAnimales = new javax.swing.JList<>();
        botonEliminarAnimal = new javax.swing.JButton();
        botonAgregarAnimal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botonLimpiarFormulario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tipoAnimalCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        razaText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edadText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pesoText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        colorText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        alturaText = new javax.swing.JTextField();
        resultadoLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(null);

        jLabel1.setText("Animales Administrador");
        add(jLabel1);
        jLabel1.setBounds(170, 10, 240, 15);

        listaAnimales.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaAnimalesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaAnimales);

        jScrollPane2.setViewportView(jScrollPane1);

        add(jScrollPane2);
        jScrollPane2.setBounds(30, 70, 480, 120);

        botonEliminarAnimal.setText("Eliminar Animal");
        botonEliminarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarAnimalActionPerformed(evt);
            }
        });
        add(botonEliminarAnimal);
        botonEliminarAnimal.setBounds(30, 210, 190, 25);

        botonAgregarAnimal.setText("Agregar Animal");
        botonAgregarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarAnimalActionPerformed(evt);
            }
        });
        add(botonAgregarAnimal);
        botonAgregarAnimal.setBounds(310, 440, 190, 25);

        jLabel2.setText("Formulario Agregar Animal");
        add(jLabel2);
        jLabel2.setBounds(30, 260, 300, 15);

        botonLimpiarFormulario.setText("Limpiar Formulario");
        botonLimpiarFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarFormularioActionPerformed(evt);
            }
        });
        add(botonLimpiarFormulario);
        botonLimpiarFormulario.setBounds(30, 440, 190, 25);

        jLabel3.setText("Tipo Animal :");
        add(jLabel3);
        jLabel3.setBounds(30, 300, 110, 15);

        tipoAnimalCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perro", "Gato"}));
        tipoAnimalCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoAnimalComboActionPerformed(evt);
            }
        });
        add(tipoAnimalCombo);
        tipoAnimalCombo.setBounds(140, 300, 130, 24);

        jLabel4.setText("Raza :");
        add(jLabel4);
        jLabel4.setBounds(290, 300, 70, 15);
        add(razaText);
        razaText.setBounds(360, 300, 130, 19);

        jLabel5.setText("Edad :");
        add(jLabel5);
        jLabel5.setBounds(30, 340, 110, 15);
        add(edadText);
        edadText.setBounds(140, 340, 130, 19);

        jLabel6.setText("Peso :");
        add(jLabel6);
        jLabel6.setBounds(290, 340, 44, 15);
        add(pesoText);
        pesoText.setBounds(360, 340, 130, 19);

        jLabel7.setText("Color :");
        add(jLabel7);
        jLabel7.setBounds(30, 380, 110, 15);
        add(colorText);
        colorText.setBounds(140, 380, 130, 19);

        jLabel8.setText("Altura :");
        add(jLabel8);
        jLabel8.setBounds(290, 380, 70, 15);
        add(alturaText);
        alturaText.setBounds(360, 380, 130, 19);
        add(resultadoLabel);
        resultadoLabel.setBounds(30, 410, 460, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarAnimalActionPerformed

        Animal animalSeleccionado = listaAnimales.getSelectedValue();

        if(animalSeleccionado != null){

            int response = JOptionPane.showConfirmDialog(this, "¿Deseas eliminar el animal del sistema?");

            if(response == JOptionPane.OK_OPTION){

                int codigoAnimal = animalSeleccionado.getCodigoAnimal();

                String resultado = animalLogica.eliminarAnimal(codigoAnimal);

                if(resultado == "OK"){

                    resultadoLabel.setText("Se ha eliminado el animal correctamente");

                    actualizarListadoAnimales();
                }
                else
                {
                    resultadoLabel.setText(resultado);
                }
            }
        }

    }//GEN-LAST:event_botonEliminarAnimalActionPerformed

    private void botonLimpiarFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarFormularioActionPerformed
        
        razaText.setText("");
        colorText.setText("");
        edadText.setText("");
        pesoText.setText("");
        alturaText.setText("");
    }//GEN-LAST:event_botonLimpiarFormularioActionPerformed

    private void listaAnimalesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaAnimalesValueChanged
        

        
    }//GEN-LAST:event_listaAnimalesValueChanged

    private void tipoAnimalComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoAnimalComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoAnimalComboActionPerformed

    private void botonAgregarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarAnimalActionPerformed

        String tipoAnimal = tipoAnimalCombo.getSelectedItem().toString();
        String raza = razaText.getText();
        String edad = edadText.getText();
        String peso = pesoText.getText();
        String color = colorText.getText();
        String altura = alturaText.getText();

        String resultado = animalLogica.registrarAnimal(tipoAnimal, raza, edad, peso, color, altura);

        if(resultado.equals("OK")){

            actualizarListadoAnimales();
            resultadoLabel.setText("Se ha agregado el animal correctamente.");
        }
        else
        {
            resultadoLabel.setText(resultado);
        }

    }//GEN-LAST:event_botonAgregarAnimalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alturaText;
    private javax.swing.JButton botonAgregarAnimal;
    private javax.swing.JButton botonEliminarAnimal;
    private javax.swing.JButton botonLimpiarFormulario;
    private javax.swing.JTextField colorText;
    private javax.swing.JTextField edadText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Animal> listaAnimales;
    private javax.swing.JTextField pesoText;
    private javax.swing.JTextField razaText;
    private javax.swing.JLabel resultadoLabel;
    private javax.swing.JComboBox<String> tipoAnimalCombo;
    // End of variables declaration//GEN-END:variables
}
