/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegio.josefelixrestrepo.acw.interfaz;

import colegio.josefelixrestrepo.acw.basededatos.Animal;
import colegio.josefelixrestrepo.acw.basededatos.Usuario;
import colegio.josefelixrestrepo.acw.logica.AnimalLogica;
import colegio.josefelixrestrepo.acw.logica.UsuarioLogica;

import javax.swing.*;
import java.util.List;

/**
 *
 * @author nancho313
 */
public class MisAnimalesPanel extends javax.swing.JPanel {

    private Usuario usuario;
    private AnimalLogica animalLogica;
    private UsuarioLogica usuarioLogica;

    /**
     * Creates new form MisAnimalesPanel
     */
    public MisAnimalesPanel() {
        initComponents();
    }

    public MisAnimalesPanel(Usuario usuario){

        this.usuario = usuario;
        animalLogica = new AnimalLogica();
        usuarioLogica = new UsuarioLogica();
        initComponents();
        listaAnimalesAdoptados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        actualizarListadoAnimales();
        setSize(534, 333);
    }

    public void actualizarListadoAnimales(){

        List<Animal> animales = usuarioLogica.obtenerAnimalesDeUsuario(usuario.getCedula());
        Animal[] animalData = null;
        if(animales != null){

            animalData = new Animal[animales.size()];
            this.listaAnimalesAdoptados.setListData(animales.toArray(animalData));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAnimalesAdoptados = new javax.swing.JList<>();
        regresarAnimalBoton = new javax.swing.JButton();
        resultadoLabel = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setText("Mis Animales");
        add(jLabel1);
        jLabel1.setBounds(210, 20, 160, 15);

        jScrollPane1.setViewportView(listaAnimalesAdoptados);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 490, 160);

        regresarAnimalBoton.setText("Regresar Animal");
        regresarAnimalBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarAnimalBotonActionPerformed(evt);
            }
        });
        add(regresarAnimalBoton);
        regresarAnimalBoton.setBounds(20, 260, 210, 25);
        add(resultadoLabel);
        resultadoLabel.setBounds(20, 230, 490, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void regresarAnimalBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarAnimalBotonActionPerformed

        Animal animalSeleccionado = listaAnimalesAdoptados.getSelectedValue();

        if(animalSeleccionado != null){

            int resultadoConfirmar = JOptionPane.showConfirmDialog(this, "¿Desea regresar el animal adoptado?");

            if(resultadoConfirmar == JOptionPane.OK_OPTION){

                String resultado = usuarioLogica.regresarAnimal(animalSeleccionado.getCodigoAnimal());

                if(resultado.equals("OK")){

                    resultadoLabel.setText("Se ha regresado el animal correctamente.");
                    actualizarListadoAnimales();
                }
                else
                {
                    resultadoLabel.setText(resultado);
                }
            }
        }
    }//GEN-LAST:event_regresarAnimalBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel resultadoLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Animal> listaAnimalesAdoptados;
    private javax.swing.JButton regresarAnimalBoton;
    // End of variables declaration//GEN-END:variables
}
