/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegio.josefelixrestrepo.acw.interfaz;

/**
 *
 * @author JULIAN RUEDA
 */
public class VentanaInicialFrame extends javax.swing.JFrame {

    /**
     * Creates new form ventanaInicial
     */
    public VentanaInicialFrame() {
        initComponents();
        registroUsuarioFrame = new RegistroUsuarioFrame(this);
        administradorFrame = new RegistrarAdministradorFrame(this);
        setSize(500, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonUsuario = new javax.swing.JButton();
        botonAdministrador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etiquetaUsuario = new javax.swing.JLabel();
        etiquetaContrasenia = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        campoContracenia = new javax.swing.JTextField();
        botonIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botonUsuario.setText("Usuario");
        botonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonUsuario);
        botonUsuario.setBounds(40, 240, 110, 23);

        botonAdministrador.setText("Administrador");
        botonAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(botonAdministrador);
        botonAdministrador.setBounds(230, 240, 130, 23);

        jLabel1.setText("Registar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 200, 60, 14);

        jLabel2.setText("Login");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 20, 70, 14);

        etiquetaUsuario.setText("Usuario:");
        getContentPane().add(etiquetaUsuario);
        etiquetaUsuario.setBounds(50, 70, 80, 14);

        etiquetaContrasenia.setText("Contraseña:");
        getContentPane().add(etiquetaContrasenia);
        etiquetaContrasenia.setBounds(50, 110, 70, 14);
        getContentPane().add(campoUsuario);
        campoUsuario.setBounds(200, 70, 120, 20);

        campoContracenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContraceniaActionPerformed(evt);
            }
        });
        getContentPane().add(campoContracenia);
        campoContracenia.setBounds(200, 100, 120, 20);

        botonIniciarSesion.setText("Iniciar sesion");
        getContentPane().add(botonIniciarSesion);
        botonIniciarSesion.setBounds(140, 160, 130, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdministradorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.administradorFrame.setVisible(true);
    }//GEN-LAST:event_botonAdministradorActionPerformed

    private void campoContraceniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContraceniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContraceniaActionPerformed

    private void botonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuarioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.registroUsuarioFrame.setVisible(true);
    }//GEN-LAST:event_botonUsuarioActionPerformed

    public static void main(String... args){
        
        VentanaInicialFrame ventanaInicialFrame = new VentanaInicialFrame();
        ventanaInicialFrame.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
   
    private RegistroUsuarioFrame registroUsuarioFrame;
    private RegistrarAdministradorFrame administradorFrame;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdministrador;
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JButton botonUsuario;
    private javax.swing.JTextField campoContracenia;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel etiquetaContrasenia;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
