/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegio.josefelixrestrepo.acw.interfaz;

import colegio.josefelixrestrepo.acw.basededatos.Administrador;
import colegio.josefelixrestrepo.acw.basededatos.Usuario;
import colegio.josefelixrestrepo.acw.logica.IniciarSesionLogica;

/**
 *
 * @author JULIAN RUEDA
 */
public class VentanaInicialFrame extends javax.swing.JFrame {

    /**
     * Creates new form ventanaInicial
     */
    public VentanaInicialFrame() {
        initComponents();
        registroUsuarioFrame = new RegistroUsuarioFrame(this);
        administradorFrame = new RegistrarAdministradorFrame(this);
        setSize(476, 249);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonUsuario = new javax.swing.JButton();
        botonAdministrador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etiquetaUsuario = new javax.swing.JLabel();
        etiquetaContrasenia = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        botonIniciarSesion = new javax.swing.JButton();
        campoContracenia = new javax.swing.JPasswordField();
        respuestaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botonUsuario.setText("Usuario");
        botonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonUsuario);
        botonUsuario.setBounds(30, 160, 190, 25);

        botonAdministrador.setText("Administrador");
        botonAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(botonAdministrador);
        botonAdministrador.setBounds(270, 160, 190, 25);

        jLabel1.setText("Registar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 130, 120, 15);

        jLabel2.setText("Login");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 70, 15);

        etiquetaUsuario.setText("Usuario:");
        getContentPane().add(etiquetaUsuario);
        etiquetaUsuario.setBounds(30, 50, 120, 15);

        etiquetaContrasenia.setText("Contraseña:");
        getContentPane().add(etiquetaContrasenia);
        etiquetaContrasenia.setBounds(30, 75, 120, 20);
        getContentPane().add(campoUsuario);
        campoUsuario.setBounds(160, 50, 120, 19);

        botonIniciarSesion.setText("Iniciar sesion");
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(botonIniciarSesion);
        botonIniciarSesion.setBounds(300, 50, 160, 25);
        getContentPane().add(campoContracenia);
        campoContracenia.setBounds(160, 80, 120, 19);
        getContentPane().add(respuestaLabel);
        respuestaLabel.setBounds(30, 110, 430, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdministradorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.administradorFrame.setVisible(true);
    }//GEN-LAST:event_botonAdministradorActionPerformed

    private void campoContraceniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContraceniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContraceniaActionPerformed

    private void botonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuarioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.registroUsuarioFrame.setVisible(true);
    }//GEN-LAST:event_botonUsuarioActionPerformed

    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt){


        String username = campoUsuario.getText();
        String password = campoContracenia.getText();

        IniciarSesionLogica iniciarSesionLogica = new IniciarSesionLogica();

        try {

            Administrador administrador = iniciarSesionLogica.iniciarSesionConAdministrador(username, password);

            if(administrador != null){

                MenuFrame menuFrame = new MenuFrame(administrador);
                menuFrame.setVisible(Boolean.TRUE);
                this.setVisible(Boolean.FALSE);
            }

            Usuario usuario = iniciarSesionLogica.iniciarSesionConUsuario(username, password);

            if(usuario != null){

                MenuFrame menuFrame = new MenuFrame(usuario);
                menuFrame.setVisible(Boolean.TRUE);
                this.setVisible(Boolean.FALSE);
            }
            else
            {
                respuestaLabel.setText("El usuario o administrador no existe con las credenciales ingresadas.");
            }

        } catch (Exception e) {

            respuestaLabel.setText(e.getMessage());
        }
    }

    public static void main(String... args) {

        VentanaInicialFrame ventanaInicialFrame = new VentanaInicialFrame();
        ventanaInicialFrame.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */

    private RegistroUsuarioFrame registroUsuarioFrame;
    private RegistrarAdministradorFrame administradorFrame;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdministrador;
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JButton botonUsuario;
    private javax.swing.JPasswordField campoContracenia;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel etiquetaContrasenia;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel respuestaLabel;
    // End of variables declaration//GEN-END:variables
}
